# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-11-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('ulogo', models.FileField(default='default.jpg', upload_to='images', verbose_name='用户头像')),
                ('urealname', models.CharField(default='', max_length=20, verbose_name='真实姓名')),
                ('uzhengjian_tel', models.CharField(default='', max_length=18, verbose_name='证件号码')),
                ('usex', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('ucredit', models.CharField(default='', max_length=5, verbose_name='信誉分')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
